name: SkyLands-SkyPvP
version: 1.0
main: me.skylands.skypvp.SkyLands
depend: [Vault, Votifier, PermissionsEx, ASkyBlock]
commands:
  rawbc:
  motd:
  disco:
  rename:
  peace:
    aliases: [friede]
  stats:
  level:
  levelserver:
  levelshop:
  clan:
  vote:
  discord:
  report:
  spectate:
    aliases: [spec]
  teamchat:
    aliases: [tc]
  kit:
  anvil:
    aliases: [amboss]
  bottle:
  fill:
  cook:
  globalmute:
  giveall:
  clearchat:
    aliases: [cc]
  cmdspy:
  ping:
  setstats:
  alt:
    aliases: [alts, accounts]
  apply:
    aliases: [bewerben]
  help:
    aliases: [hilfe, ?]
  huansohn: